# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Sobre
    url: /
    weight: 10
  - name: Experiência
    url: experience/
    weight: 20
  - name: Publicações
    #url: /#papers
    url: publication/
    weight: 30
  - name: Comunicações
    url: /#talks
    weight: 40
  - name: Blog
    url: post/
    weight: 50
  - name: Projetos
    url: projects/
    weight: 60
  # - name: Ensino
  #   url: teaching/
  #   weight: 70
